"""add Department

Revision ID: 849d9ac8ad4c
Revises: a3930eecaad7
Create Date: 2025-03-25 14:19:32.678241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849d9ac8ad4c'
down_revision = 'a3930eecaad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
