"""rename department

Revision ID: e8375a99e8f0
Revises: 849d9ac8ad4c
Create Date: 2025-03-25 14:24:18.343241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8375a99e8f0'
down_revision = '849d9ac8ad4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
